(el-get-bundle init-loader)
(el-get-bundle helm)
(el-get-bundle helm-ls-git)
(el-get-bundle helm-ag)
(el-get-bundle auto-complete)
(el-get-bundle fuzzy)
(el-get-bundle elscreen)
(el-get-bundle markdown-mode)
(el-get-bundle open-junk-file)
(el-get-bundle perl-completion)
(el-get-bundle magit)
(el-get-bundle popwin)
(el-get-bundle helm-ghq)
(el-get-bundle exec-path-from-shell)
(el-get-bundle git-gutter)
(el-get-bundle (:name flycheck :build (progn nil) :info nil))
(el-get-bundle web-mode)
(el-get-bundle typescript-mode)
(el-get-bundle tide)
(el-get-bundle company-mode)
(el-get-bundle plantuml-mode)
(el-get-bundle go-mode)
(el-get-bundle go-autocomplete)

;; el-getに無いので、githubからインストールする
;; https://github.com/syohex/emacs-helm-perldoc/releases/tag/0.07
(el-get-bundle helm-perldoc :type git :url "git@github.com:syohex/emacs-helm-perldoc.git" :checkout "18645f2065a07acce2c6b50a2f9d7a2554e532a3")
